### ISSUE TITLE
Syntax error

### ISSUE THREAD

**Issue by TGallagherM** [Combinatix/JLCPCB-Basic-Parts#2]
I have copied the ULP and Library files to the specified directories but when attempting to run ULP script I am presented with a Syntax error.
Autodesk Eagle 9.6.2 Free

![Eagle JLCPCB_basic error](https://user-images.githubusercontent.com/3893366/149544121-c6064668-72cb-403f-a2d9-f1a1349f1f68.png)

**Comment by Combinatix** [comment]
Why your filename contains an extension `.ulp(7)` ? It should be `.ulp`. Please recheck the filename, if the extension is correct.

**Comment by TGallagherM** [comment]
Something strange must have happened when I downloaded the files individually. I redownloaded as zip file an extracted the ulp to the folder and everything is fine.
