### ISSUE TITLE
Error:  line 8, column 87: This is not an EAGLE file.

### ISSUE THREAD

**Issue by TGallagherM** [Combinatix/JLCPCB-Basic-Parts#3]
Attempting to load JLCPCB library gives the following error

![Eagle JLCPCB_basic library error](https://user-images.githubusercontent.com/3893366/149545686-60bb12d8-8987-4840-b61d-e343933bfcdd.png)

**Comment by Combinatix** [comment]
There is not Line 8 , column 87 position in the "JLC PCB Basic Parts_loc.lbr". Are you sure you have the right file? The Line 8 contains tag `<settings>`. See the https://github.com/Combinatix/JLCPCB-Basic-Parts/blob/main/JLC%20PCB%20Basic%20Parts_loc.lbr

Anybody else have the same issue? I can't reproduce the error. That error does not make a sense?!

**Comment by TGallagherM** [comment]
Something strange must have happened when I downloaded the files individually.  I redownloaded as zip file an extracted the library to the folder and everything is fine.
