### ISSUE TITLE
Fusion360

### ISSUE THREAD

**Issue by SpartanJRU** [Combinatix/JLCPCB-Basic-Parts#4]
The library works great in Fusion 360 but when using the ULP exporter it says the files have been saved to the project folder but I don't know where that would be with Fusion. Can the file location be listed in the popup?
It was a little confusing that the library is called JLCPCB but the part numbers are from LCSC. Same company family but the numbers don't come up when searching JLCPCB.

**Comment by Combinatix** [comment]
I think it should be possible. In the meantime, you can try to search for the `*.bom` and `*.cpl` files using some file search tool.

Regarding the JLCPCB vs LCSC you're right. I've intentionally included both names, so it is easier to google. Anyway, it is not really an issue.
